//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemProgramm {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemProgramm.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        public static string CardCpu {
            get {
                return ResourceManager.GetString("CardCpu", resourceCulture);
            }
        }

        public static string CardDevices {
            get {
                return ResourceManager.GetString("CardDevices", resourceCulture);
            }
        }

        public static string CardGpu {
            get {
                return ResourceManager.GetString("CardGpu", resourceCulture);
            }
        }

        public static string CardMemory {
            get {
                return ResourceManager.GetString("CardMemory", resourceCulture);
            }
        }

        public static string CardNetwork {
            get {
                return ResourceManager.GetString("CardNetwork", resourceCulture);
            }
        }

        public static string CardStorage {
            get {
                return ResourceManager.GetString("CardStorage", resourceCulture);
            }
        }

        public static string CpuCoresThreads {
            get {
                return ResourceManager.GetString("CpuCoresThreads", resourceCulture);
            }
        }

        public static string DeviceCount {
            get {
                return ResourceManager.GetString("DeviceCount", resourceCulture);
            }
        }

        public static string LoadPercent {
            get {
                return ResourceManager.GetString("LoadPercent", resourceCulture);
            }
        }

        public static string MemoryDetail {
            get {
                return ResourceManager.GetString("MemoryDetail", resourceCulture);
            }
        }

        public static string NetworkTraffic {
            get {
                return ResourceManager.GetString("NetworkTraffic", resourceCulture);
            }
        }

        public static string OverviewPlaceholder {
            get {
                return ResourceManager.GetString("OverviewPlaceholder", resourceCulture);
            }
        }

        public static string PageCpu {
            get {
                return ResourceManager.GetString("PageCpu", resourceCulture);
            }
        }

        public static string PageGpu {
            get {
                return ResourceManager.GetString("PageGpu", resourceCulture);
            }
        }

        public static string PageMemory {
            get {
                return ResourceManager.GetString("PageMemory", resourceCulture);
            }
        }

        public static string PageNetwork {
            get {
                return ResourceManager.GetString("PageNetwork", resourceCulture);
            }
        }

        public static string PageNotImplemented {
            get {
                return ResourceManager.GetString("PageNotImplemented", resourceCulture);
            }
        }

        public static string PageOverview {
            get {
                return ResourceManager.GetString("PageOverview", resourceCulture);
            }
        }

        public static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }

        public static string PageStorage {
            get {
                return ResourceManager.GetString("PageStorage", resourceCulture);
            }
        }

        public static string SettingsAppearance {
            get {
                return ResourceManager.GetString("SettingsAppearance", resourceCulture);
            }
        }

        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }

        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }

        public static string StorageDetail {
            get {
                return ResourceManager.GetString("StorageDetail", resourceCulture);
            }
        }

        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }

        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }

        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }

        public static string TemperatureCelsius {
            get {
                return ResourceManager.GetString("TemperatureCelsius", resourceCulture);
            }
        }

        public static string UnitGigabitPerSecond {
            get {
                return ResourceManager.GetString("UnitGigabitPerSecond", resourceCulture);
            }
        }

        public static string UnitGigabyte {
            get {
                return ResourceManager.GetString("UnitGigabyte", resourceCulture);
            }
        }

        public static string UnitKilobitPerSecond {
            get {
                return ResourceManager.GetString("UnitKilobitPerSecond", resourceCulture);
            }
        }

        public static string UnitMegabitPerSecond {
            get {
                return ResourceManager.GetString("UnitMegabitPerSecond", resourceCulture);
            }
        }

        public static string UnitTerabyte {
            get {
                return ResourceManager.GetString("UnitTerabyte", resourceCulture);
            }
        }

        public static string UsedPercent {
            get {
                return ResourceManager.GetString("UsedPercent", resourceCulture);
            }
        }

        public static string ValueUnknown {
            get {
                return ResourceManager.GetString("ValueUnknown", resourceCulture);
            }
        }
    }
}
