//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemProgramm {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemProgramm.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        public static string CardCpu {
            get {
                return ResourceManager.GetString("CardCpu", resourceCulture);
            }
        }

        public static string CardDetails {
            get {
                return ResourceManager.GetString("CardDetails", resourceCulture);
            }
        }

        public static string CardDevices {
            get {
                return ResourceManager.GetString("CardDevices", resourceCulture);
            }
        }

        public static string CardGpu {
            get {
                return ResourceManager.GetString("CardGpu", resourceCulture);
            }
        }

        public static string CardMemory {
            get {
                return ResourceManager.GetString("CardMemory", resourceCulture);
            }
        }

        public static string CardNetwork {
            get {
                return ResourceManager.GetString("CardNetwork", resourceCulture);
            }
        }

        public static string CardStorage {
            get {
                return ResourceManager.GetString("CardStorage", resourceCulture);
            }
        }

        public static string ChartNow {
            get {
                return ResourceManager.GetString("ChartNow", resourceCulture);
            }
        }

        public static string ChartWindow {
            get {
                return ResourceManager.GetString("ChartWindow", resourceCulture);
            }
        }

        public static string CpuCoresThreads {
            get {
                return ResourceManager.GetString("CpuCoresThreads", resourceCulture);
            }
        }

        public static string DetailBusClock {
            get {
                return ResourceManager.GetString("DetailBusClock", resourceCulture);
            }
        }

        public static string DetailCache {
            get {
                return ResourceManager.GetString("DetailCache", resourceCulture);
            }
        }

        public static string DetailClock {
            get {
                return ResourceManager.GetString("DetailClock", resourceCulture);
            }
        }

        public static string DetailCores {
            get {
                return ResourceManager.GetString("DetailCores", resourceCulture);
            }
        }

        public static string DetailFamily {
            get {
                return ResourceManager.GetString("DetailFamily", resourceCulture);
            }
        }

        public static string DetailFeatures {
            get {
                return ResourceManager.GetString("DetailFeatures", resourceCulture);
            }
        }

        public static string DetailLoad {
            get {
                return ResourceManager.GetString("DetailLoad", resourceCulture);
            }
        }

        public static string DetailMaxClock {
            get {
                return ResourceManager.GetString("DetailMaxClock", resourceCulture);
            }
        }

        public static string DetailMemoryClock {
            get {
                return ResourceManager.GetString("DetailMemoryClock", resourceCulture);
            }
        }

        public static string DetailModel {
            get {
                return ResourceManager.GetString("DetailModel", resourceCulture);
            }
        }

        public static string DetailPower {
            get {
                return ResourceManager.GetString("DetailPower", resourceCulture);
            }
        }

        public static string DetailPowerCores {
            get {
                return ResourceManager.GetString("DetailPowerCores", resourceCulture);
            }
        }

        public static string DetailSocket {
            get {
                return ResourceManager.GetString("DetailSocket", resourceCulture);
            }
        }

        public static string DetailTemperature {
            get {
                return ResourceManager.GetString("DetailTemperature", resourceCulture);
            }
        }

        public static string DetailVendor {
            get {
                return ResourceManager.GetString("DetailVendor", resourceCulture);
            }
        }

        public static string DetailVideoMemory {
            get {
                return ResourceManager.GetString("DetailVideoMemory", resourceCulture);
            }
        }

        public static string DeviceCount {
            get {
                return ResourceManager.GetString("DeviceCount", resourceCulture);
            }
        }

        public static string LoadPercent {
            get {
                return ResourceManager.GetString("LoadPercent", resourceCulture);
            }
        }

        public static string MemoryDetail {
            get {
                return ResourceManager.GetString("MemoryDetail", resourceCulture);
            }
        }

        public static string NetworkTraffic {
            get {
                return ResourceManager.GetString("NetworkTraffic", resourceCulture);
            }
        }

        public static string MetricLoad {
            get {
                return ResourceManager.GetString("MetricLoad", resourceCulture);
            }
        }

        public static string MetricTemperature {
            get {
                return ResourceManager.GetString("MetricTemperature", resourceCulture);
            }
        }

        public static string OverviewPlaceholder {
            get {
                return ResourceManager.GetString("OverviewPlaceholder", resourceCulture);
            }
        }

        public static string PageCpu {
            get {
                return ResourceManager.GetString("PageCpu", resourceCulture);
            }
        }

        public static string PageGpu {
            get {
                return ResourceManager.GetString("PageGpu", resourceCulture);
            }
        }

        public static string PageMemory {
            get {
                return ResourceManager.GetString("PageMemory", resourceCulture);
            }
        }

        public static string PageNetwork {
            get {
                return ResourceManager.GetString("PageNetwork", resourceCulture);
            }
        }

        public static string PageNotImplemented {
            get {
                return ResourceManager.GetString("PageNotImplemented", resourceCulture);
            }
        }

        public static string PageOverview {
            get {
                return ResourceManager.GetString("PageOverview", resourceCulture);
            }
        }

        public static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }

        public static string PageStorage {
            get {
                return ResourceManager.GetString("PageStorage", resourceCulture);
            }
        }

        public static string PercentValue {
            get {
                return ResourceManager.GetString("PercentValue", resourceCulture);
            }
        }

        public static string RightsGranted {
            get {
                return ResourceManager.GetString("RightsGranted", resourceCulture);
            }
        }

        public static string RightsMissing {
            get {
                return ResourceManager.GetString("RightsMissing", resourceCulture);
            }
        }

        public static string RightsRestart {
            get {
                return ResourceManager.GetString("RightsRestart", resourceCulture);
            }
        }

        public static string SettingsAppearance {
            get {
                return ResourceManager.GetString("SettingsAppearance", resourceCulture);
            }
        }

        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }

        public static string SettingsRights {
            get {
                return ResourceManager.GetString("SettingsRights", resourceCulture);
            }
        }

        public static string SettingsRunElevated {
            get {
                return ResourceManager.GetString("SettingsRunElevated", resourceCulture);
            }
        }

        public static string SettingsRunElevatedHint {
            get {
                return ResourceManager.GetString("SettingsRunElevatedHint", resourceCulture);
            }
        }

        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }

        public static string StorageDetail {
            get {
                return ResourceManager.GetString("StorageDetail", resourceCulture);
            }
        }

        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }

        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }

        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }

        public static string TemperatureCelsius {
            get {
                return ResourceManager.GetString("TemperatureCelsius", resourceCulture);
            }
        }

        public static string UnitCelsius {
            get {
                return ResourceManager.GetString("UnitCelsius", resourceCulture);
            }
        }

        public static string UnitGigabitPerSecond {
            get {
                return ResourceManager.GetString("UnitGigabitPerSecond", resourceCulture);
            }
        }

        public static string UnitGigabyte {
            get {
                return ResourceManager.GetString("UnitGigabyte", resourceCulture);
            }
        }

        public static string UnitKilobitPerSecond {
            get {
                return ResourceManager.GetString("UnitKilobitPerSecond", resourceCulture);
            }
        }

        public static string UnitMegabitPerSecond {
            get {
                return ResourceManager.GetString("UnitMegabitPerSecond", resourceCulture);
            }
        }

        public static string UnitKilobyte {
            get {
                return ResourceManager.GetString("UnitKilobyte", resourceCulture);
            }
        }

        public static string UnitMegabyte {
            get {
                return ResourceManager.GetString("UnitMegabyte", resourceCulture);
            }
        }

        public static string UnitMegahertzValue {
            get {
                return ResourceManager.GetString("UnitMegahertzValue", resourceCulture);
            }
        }

        public static string UnitPercent {
            get {
                return ResourceManager.GetString("UnitPercent", resourceCulture);
            }
        }

        public static string UnitWattValue {
            get {
                return ResourceManager.GetString("UnitWattValue", resourceCulture);
            }
        }

        public static string UnitTerabyte {
            get {
                return ResourceManager.GetString("UnitTerabyte", resourceCulture);
            }
        }

        public static string UsedPercent {
            get {
                return ResourceManager.GetString("UsedPercent", resourceCulture);
            }
        }

        public static string ValueUnknown {
            get {
                return ResourceManager.GetString("ValueUnknown", resourceCulture);
            }
        }
    }
}
